#!/bin/sh -ex
./Dockerfile.build debian/bullseye # deb11
./Dockerfile.build ubuntu/focal    # ubu20.04
./Dockerfile.build debian/buster   # deb10
#./Dockerfile.build ubuntu/bionic  # ubu18.04
#./Dockerfile.build debian/stretch # deb9
#./Dockerfile.build ubuntu/xenial  # ubu16.04
#./Dockerfile.build debian/jessie  # deb8
